### ISSUE TITLE
Syntax Highlighter Treats `/*` in String as Start of Block Comment

### ISSUE THREAD

**Issue by Roberttmoon** [syohex/emacs-hcl-mode#10]
HCL-mode will catch `/*` as the start of a block comment if its in a string.

example

 ```
data "aws_iam_policy_document" "my_policy" {
  statement {
    sid      = "blah"
    action = ["*"]

    resource = [
      "${format("arn:aws:ssm:%v:%v:parameter/*", var.region, var.account_id)}"
    ]
  }
}
```

everything after the `/*` in the format interpolation was styled as a block comment.

PS: I'm a huge fan of both hcl-mode and terraform-mode :D

**Comment by purcell** [comment]
I believe this is no longer the case, and that this issue can be closed.
