### ISSUE TITLE
Please set LICENSE field in repository metadata

### ISSUE THREAD

**Issue by ifradeo** [syohex/emacs-hcl-mode#12]
Code has header for GPLv3, but the license in the repository metadata is not set:

$ curl https://api.github.com/repos/syohex/emacs-hcl-mode
(The returned JSON has a license field when the metadata is set in github).

This field is helpful for automated tools and should be easy to set in the github website.

**Comment by syohex** [comment]
https://github.com/purcell/emacs-hcl-mode

This package is no longer maintained. If you have an issue, please send it to https://github.com/purcell/emacs-hcl-mode
