### ISSUE TITLE
Please include installation instructions for non-MELPA users

### ISSUE THREAD

**Issue by bish0polis** [syohex/emacs-hcl-mode#14]
Some people cannot use MELPA.  

Can we please have a simple installation comment included, so that we can ensure we're not missing a step?  I know -- it's easy to install, with a copy here and there.  Please include that so we know we've done the simple by-hand step required, for our assurance.

Thanks!

**Comment by syohex** [comment]
https://github.com/purcell/emacs-hcl-mode

Sorry for late reply. This package is no longer maintained. If you have an issue, please report above URL

**Comment by bish0polis** [comment]
> please report above URL

Are you sure?  I'm not sure to whom I'd report the URL, nor what offense I'd be reporting.

Thanks, though!  Don't forget to put a notice on the Readme that it's abandoned.
