### ISSUE TITLE
Herodoc breaks syntax highlighting

### ISSUE THREAD

**Issue by KeenS** [syohex/emacs-hcl-mode#2]
This configuration breaks syntax highlighting _just after file opened_.

I know [this issue](https://github.com/syohex/emacs-terraform-mode/issues/14) but in this case, you don't need to do anything to break highlight.

BTW, though troubles are in editing terraform config, I found this issue occur with mere hcl-mode so I opened to this issue to hcl-mode repository.

``` hcl
resource "null_resource" "test_resource" {
  count = "${var.test_count}"

  # Changes to any instance of the cluster requires re-provisioning
  triggers {
    cluster_instance_ids = "${join(",", aws_instance.test.*.id)}"
  }

  connection {
    host = "${element(aws_instance.test.*.private_ip, count.index)}"
    user = "centos"
    timeout = "10m"
    bastion_host = "${var.bastion_host}"
    bastion_user = "${var.bastion_user}"
  }

  provisioner "remote-exec" {
    inline = <<EOF
some command

EOF
  }
}
```

![screenshot from 2016-10-04 14-35-05](https://cloud.githubusercontent.com/assets/4434568/19063664/c61a31dc-8a3f-11e6-9713-2514cb4b43ae.png)

**Comment by syohex** [comment]
Thanks for issue. I'll check.

**Comment by syohex** [comment]
Sorry belated response. I have rewritten here document highlighting based on shell-script-mode. I suppose it fixes this issue.

<img width="707" alt="a" src="https://cloud.githubusercontent.com/assets/554281/21580836/b684ca2c-d056-11e6-9ea4-38a32b78bd11.png">
