### ISSUE TITLE
hcl-mode not found

### ISSUE THREAD

**Issue by cgutshal** [syohex/emacs-hcl-mode#6]
When doing a package-install its unable to find the following:

http://melpa.milkbox.net/packages/hcl-mode-20160502.1700.el: Not found      

Is the repo out of date on melpa?

Thanks

**Comment by briansorahan** [comment]
I see something similar

```
http://melpa.milkbox.net/packages/hcl-mode-20161006.950.el: Not found
```

**Comment by purcell** [comment]
The answer here was to run `M-x package-refresh-contents`. This issue can be closed.
