### ISSUE TITLE
Multi-line string interpolation highlighting

### ISSUE THREAD

**Issue by ivan-m** [syohex/emacs-hcl-mode#7]
If a string interpolation is split over multiple lines (e.g. the [tags example](https://www.terraform.io/docs/configuration/locals.html) in local variables for Terraform) then `hcl-mode` will treat it as a plain string (though the sub-strings will end up with the `default` face).

I think it may be because you ensure `\n` does exist within the string, but just removing it from `hcl--string-interpolation-regexp` didn't seem to change anything.

**Comment by asnr** [comment]
Visually, for me it looks like:

![image](https://user-images.githubusercontent.com/3961287/33501780-f110462a-d731-11e7-9fa9-028ad942b7ed.png)

**Comment by syohex** [comment]
https://github.com/purcell/emacs-hcl-mode

This package is no longer maintained. If you have an issue, please send it to https://github.com/purcell/emacs-hcl-mode
