### ISSUE TITLE
Nested string interpolation

### ISSUE THREAD

**Issue by ivan-m** [syohex/emacs-hcl-mode#8]
This is valid Hashicorp (specifically Terraform) code:

```hcl
tags = "${merge(var.default_tags, map("Name", "${var.default_name}"}"
```

However, `hcl-mode` assumes that the entire string interpolation ends at the first `}"`, and thus the trailing `}"` at the end is treated as a generic string.

**Comment by syohex** [comment]
https://github.com/purcell/emacs-hcl-mode

Sorry for late reply. This package is no longer maintained. If you have an issue, please report above URL
